### ISSUE TITLE
Spreadsheet cleared

### ISSUE THREAD

**Issue by DanjelRicci** [bgr/brainstormer#1]
Looks like some funny guy deleted all the entries in the spreadsheet and left only one, saying "Petting the robots". It should be possible to revert back the document to a previous revision, right?

![screenshot 2013-12-14 14 25 07](https://f.cloud.github.com/assets/5889576/1748505/2f26780c-64c3-11e3-8965-9877fd310c2b.png)

**Comment by bgr** [comment]
Restored, thanks for the notice!
