### ISSUE TITLE
Spreadsheet messed up

### ISSUE THREAD

**Issue by DanjelRicci** [bgr/brainstormer#2]
Hello! I continue coming here and using this brainstormer from time to time.
Looks like now someone has messed up the spreadsheet changing things with random characters like "gfdghj" and such. Got any backup? Thanks!

**Comment by bgr** [comment]
Hey, thanks for reporting! Yes, there's a revision history (Google Docs records every individual keypress btw). I've restored last version before it was vandalized. Glad to hear people still use it, thanks again!
